name: Avatar Bindings CI

on:
  pull_request:
    branches:
      - main

jobs:
  validate-and-seal:
    name: validate-and-seal
    runs-on: ubuntu-latest
    env:
      CONSOLIDATED_MANIFEST: dist/consolidated-manifest.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/npm-shrinkwrap.json

      - name: Install avv CLI
        run: |
          set -euo pipefail
          trap 'echo "::error::Failed to install avv CLI"' ERR
          npm install -g avv
        shell: bash

      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install Python dependencies
        run: |
          set -euo pipefail
          trap 'echo "::error::Python dependency installation failed"' ERR
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "::error::requirements.txt not found"
            exit 1
          fi
        shell: bash

      - name: Validate manifest schema
        run: |
          set -euo pipefail
          trap 'echo "::error::Manifest schema validation failed"' ERR
          if [ ! -f manifest.json ]; then
            echo "::error::manifest.json not found"
            exit 1
          fi
          npx --yes ajv-cli validate -d manifest.json
        shell: bash

      - name: Consolidate manifest
        run: |
          set -euo pipefail
          trap 'echo "::error::Manifest consolidation failed"' ERR
          mkdir -p dist
          node scripts/consolidate.js
          if [ ! -f "$CONSOLIDATED_MANIFEST" ]; then
            echo "::error::Expected consolidated manifest at $CONSOLIDATED_MANIFEST"
            exit 1
          fi
        shell: bash

      - name: Hash and sign consolidated manifest
        run: |
          set -euo pipefail
          trap 'echo "::error::Hashing or signing failed"' ERR
          if [ -z "${MANIFEST_PRIVATE_KEY:-}" ]; then
            echo "::error::MANIFEST_PRIVATE_KEY secret is not set"
            exit 1
          fi
          if [ ! -f "$CONSOLIDATED_MANIFEST" ]; then
            echo "::error::Consolidated manifest not found at $CONSOLIDATED_MANIFEST"
            exit 1
          fi
          printf '%s\n' "$MANIFEST_PRIVATE_KEY" > manifest_signing_key.pem
          chmod 600 manifest_signing_key.pem
          sha256sum "$CONSOLIDATED_MANIFEST" | tee dist/consolidated-manifest.sha256
          openssl dgst -sha256 -sign manifest_signing_key.pem -out dist/consolidated-manifest.sig.bin "$CONSOLIDATED_MANIFEST"
          openssl base64 -in dist/consolidated-manifest.sig.bin -out dist/consolidated-manifest.sig
          rm dist/consolidated-manifest.sig.bin
          rm manifest_signing_key.pem
        shell: bash
        env:
          MANIFEST_PRIVATE_KEY: ${{ secrets.MANIFEST_PRIVATE_KEY }}

      - name: Emit ledger event
        run: |
          set -euo pipefail
          trap 'echo "::error::Failed to emit ledger event"' ERR
          if [ -z "${LEDGER_ENDPOINT:-}" ]; then
            echo "::error::LEDGER_ENDPOINT secret is not set"
            exit 1
          fi
          if [ -z "${LEDGER_API_KEY:-}" ]; then
            echo "::error::LEDGER_API_KEY secret is not set"
            exit 1
          fi
          HASH_VALUE=$(cut -d ' ' -f1 dist/consolidated-manifest.sha256)
          curl -sSf -X POST "$LEDGER_ENDPOINT" \
            -H "Authorization: Bearer $LEDGER_API_KEY" \
            -H 'Content-Type: application/json' \
            -d "{\"manifestSha256\":\"$HASH_VALUE\"}"
        shell: bash
        env:
          LEDGER_API_KEY: ${{ secrets.LEDGER_API_KEY }}
          LEDGER_ENDPOINT: ${{ secrets.LEDGER_ENDPOINT }}

      - name: Upload manifest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: avatar-bindings-manifest
          path: |
            ${{ env.CONSOLIDATED_MANIFEST }}
            dist/consolidated-manifest.sha256
            dist/consolidated-manifest.sig
          if-no-files-found: error
