name: fonts-proxy-ci
on:
  pull_request: { branches: [main] }
  push: { branches: [main] }

jobs:
  lint-diff-build-test:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # OpenAPI lint + diff
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm i -g @stoplight/spectral-cli @openapitools/openapi-diff
      - run: spectral lint ./.well-known/openapi.yaml
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: OpenAPI diff (PR only)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git show ${{ github.event.pull_request.base.sha }}:.well-known/openapi.yaml > old.yaml
          git show ${{ github.event.pull_request.head.sha }}:.well-known/openapi.yaml > new.yaml
          openapi-diff old.yaml new.yaml \
            --fail-on incompatible,major \
            --report=html:openapi-diff.html \
            --report=json:openapi-diff.json
      - name: Upload diff report
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: openapi-diff-report
          path: |
            openapi-diff.html
            openapi-diff.json

      # Build + push image
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/google-fonts-proxy:latest

      # Container smoke tests
      - name: Run container
        run: |
          docker run -d --rm --name fonts-proxy \
            -e GOOGLE_FONTS_API_KEY=${{ secrets.GOOGLE_FONTS_API_KEY }} \
            -e PROXY_KEY=${{ secrets.PROXY_KEY }} \
            -p 8787:8787 ghcr.io/${{ github.repository_owner }}/google-fonts-proxy:latest
          until curl -fsS http://localhost:8787/healthz; do sleep 1; done
          curl -fsS -H "x-api-key: ${{ secrets.PROXY_KEY }}" \
            "http://localhost:8787/api/fonts/list?sort=popularity" | jq '.items[0].family' -e
          curl -fsS -H "x-api-key: ${{ secrets.PROXY_KEY }}" \
            "http://localhost:8787/api/fonts/files?family=Inter" | jq '.items | type' -e
          docker stop fonts-proxy
