name: fonts-proxy-ci
on:
  pull_request: { branches: [main] }
  push: { branches: [main] }

jobs:
  lint-diff-build-test:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    env:
      OPENAPI_PATH: .well-known/openapi.yaml
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # OpenAPI lint + diff
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm i -g @stoplight/spectral-cli @openapitools/openapi-diff
      - name: Lint OpenAPI description
        run: spectral lint "${OPENAPI_PATH}"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Prepare OpenAPI specs
        id: prep
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          set -euo pipefail
          mkdir -p .openapi-diff
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          PATH_IN_REPO="${OPENAPI_PATH}"

          if git cat-file -e "${BASE_SHA}:${PATH_IN_REPO}" 2>/dev/null; then
            git show "${BASE_SHA}:${PATH_IN_REPO}" > .openapi-diff/base.yaml
            cp "${PATH_IN_REPO}" .openapi-diff/head.yaml
            echo "HAS_BASE=true" >> "$GITHUB_OUTPUT"
          else
            echo "HAS_BASE=false" >> "$GITHUB_OUTPUT"
          fi
      - name: OpenAPI diff (PR only)
        if: ${{ github.event_name == 'pull_request' && steps.prep.outputs.HAS_BASE == 'true' }}
        run: |
          openapi-diff .openapi-diff/base.yaml .openapi-diff/head.yaml \
            --fail-on incompatible,major \
            --report=html:.openapi-diff/openapi-diff.html \
            --report=json:.openapi-diff/openapi-diff.json
      - name: Skip OpenAPI diff
        if: ${{ github.event_name == 'pull_request' && steps.prep.outputs.HAS_BASE != 'true' }}
        run: echo "No base OpenAPI spec found; treating as a new spec and skipping diff."
      - name: Upload diff report
        if: ${{ always() && github.event_name == 'pull_request' && steps.prep.outputs.HAS_BASE == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: openapi-diff-report
          path: |
            .openapi-diff/openapi-diff.html
            .openapi-diff/openapi-diff.json

      # Build + push image
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/google-fonts-proxy:latest

      # Container smoke tests
      - name: Run container
        run: |
          docker run -d --rm --name fonts-proxy \
            -e GOOGLE_FONTS_API_KEY=${{ secrets.GOOGLE_FONTS_API_KEY }} \
            -e PROXY_KEY=${{ secrets.PROXY_KEY }} \
            -p 8787:8787 ghcr.io/${{ github.repository_owner }}/google-fonts-proxy:latest
          until curl -fsS http://localhost:8787/healthz; do sleep 1; done
          curl -fsS -H "x-api-key: ${{ secrets.PROXY_KEY }}" \
            "http://localhost:8787/api/fonts/list?sort=popularity" | jq '.items[0].family' -e
          curl -fsS -H "x-api-key: ${{ secrets.PROXY_KEY }}" \
            "http://localhost:8787/api/fonts/files?family=Inter" | jq '.items | type' -e
          docker stop fonts-proxy
